ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter feather-m0-wifi,$(USEMODULE)))
  ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
    USEMODULE += atwinc15x0
  endif
endif

# setup the samd21 arduino bootloader related dependencies
include $(RIOTBOARD)/common/samd21-arduino-bootloader/Makefile.dep
